# Generated by Django 4.2.4 on 2023-09-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userfirstname', models.CharField(max_length=50)),
                ('userlastname', models.CharField(max_length=50)),
                ('userphone', models.CharField(max_length=50)),
                ('useremail', models.EmailField(max_length=50)),
                ('userpassword', models.CharField(max_length=50)),
                ('designation', models.CharField(default='User', max_length=50)),
            ],
        ),
    ]
