# Generated by Django 4.2.4 on 2023-09-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_booknow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booknow',
            old_name='bookingtime',
            new_name='ubookingtime',
        ),
    ]
