# Generated by Django 4.2.4 on 2023-09-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_turflocation_tname'),
        ('User', '0005_rename_bookingtime_booknow_ubookingtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booknow',
            name='uboookingaddress',
        ),
        migrations.AddField(
            model_name='booknow',
            name='ubookingaddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.turflocation'),
        ),
    ]
