# Generated by Django 4.2.4 on 2023-09-08 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_booknow_uboookingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.userregister'),
        ),
    ]
