# Generated by Django 4.2.4 on 2023-09-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='ubookingstatus',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
