# Generated by Django 4.2.4 on 2023-09-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_calender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='ubookingtime',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.timerange'),
        ),
    ]
