# Generated by Django 4.2.4 on 2023-09-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_delete_calender'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='upaymentstatus',
            field=models.CharField(default='unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='ubookingtime',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='User.timerange'),
        ),
    ]
